- name: Create user
  import_tasks: create_user.yml
  become: true
  
- name: Build container images if applicable
  block:
  - name: Prepare the "{{ service_systemd_name }}" build environment
    import_tasks: prepare_build.yml
    become: true
    become_user: "{{ service_user }}"
  - name: Build the "{{ service_systemd_name }}" container image
    import_tasks: build.yml
    become: true
    become_user: "{{ service_user }}"
  - name: Clean build directory
    import_tasks: clean_builddir.yml
    become: true
    become_user: "{{ service_user }}"
  when: container_images_to_build is defined
  
- name: Deploy the "{{ service_systemd_name }}" systemd unit
  import_tasks: deploy.yml
  become: true
- name: Set up port forwarding for "{{ service_systemd_name }}"
  import_tasks: port_forward.yml
  become: true

