- name: Get the service user information
  user:
    name: "{{ service_user }}"
    state: present
  register: service_user_data
  
- name: Copy service pod yaml
  copy:
    src: "{{ servideo_config_dir }}{{service_systemd_name}}/pod/service_pod.yaml"
    dest: "{{ service_user_data.home }}/service_pod.yaml"
  become: true
  become_user: "{{ service_user }}"

- name: Copy runtime directories
  include_tasks: runtime_dirs.yaml
  vars:
    selinux_labels: "{{ item.selinux_labels }}"
    directories: "{{ item.directories }}"
    service_homedir: "{{ service_user_data.home }}"
  loop: "{{ runtime_directories }}"
  when: runtime_directories is defined

- name: Create empty list of built if no container images have been built
  set_fact:
    built_container_images: "{{ [] }}"
#  when: container_images_to_build is not defined

# maybe later if registry 
#- name: prefix localhost the built container images (if applicable)
#  set_fact:
#    built_container_images: "{{ ['localhost/'] | product(container_images_to_build) | map('join') | list }}"
#  when: container_images_to_build is defined

#- name: debug
#  debug: var=built_container_images

- name: Register "{{ service_systemd_name }}" systemd unit
  vars:
    container_run_as_user: "{{ service_user }}"
    container_run_as_group: "{{ service_user }}"
    container_image_list: "{{ built_container_images + container_images_to_pull }}"
    container_name: "{{ service_systemd_name }}"
    container_pod_yaml: "{{ service_user_data.home }}/service_pod.yaml"
    container_state: running
  import_role:
    name: ikke_t.podman_container_systemd

- name: Ensure the service is started
  become: true
  become_user: "{{ service_user }}"
  systemd:
   name: "{{ service_systemd_name }}-container-pod-{{ service_user }}.service" 
   daemon-reload: yes
   scope: user
   state: started

