- name: Copy service pod yaml
  copy:
    src: "{{ servideo_config_dir }}{{service_systemd_name}}/pod/service_pod.yaml"
    dest: "{{ ansible_env.HOME }}/service_pod.yaml"
  become: true
  become_user: "{{ service_user }}"

- name: Copy runtime directories
  include_tasks: runtime_dirs.yaml
  vars:
    selinux_labels: "{{ item.selinux_labels }}"
    directories: "{{ item.directories }}"
  loop: "{{ runtime_directories }}"
  when: runtime_directories is defined

- name: Create empty list for images to pull if not defined
  set_fact:
    container_images_to_pull: "{{ [] }}"
  when: container_images_to_pull is not defined

- name: Create empty list for images to build if not defined
  set_fact:
    container_images_to_build: "{{ [] }}"
  when: container_images_to_build is not defined


- name: Register "{{ service_systemd_name }}" systemd unit
  vars:
    container_run_as_user: "{{ service_user }}"
    container_run_as_group: "{{ service_user }}"
    container_image_list: "{{ container_images_to_build + container_images_to_pull }}"
    container_name: "{{ service_systemd_name }}"
    container_pod_yaml: "{{ ansible_env.HOME }}/service_pod.yaml"
    container_state: running
  import_role:
    name: ikke_t.podman_container_systemd

- name: Ensure the service is started
  become: true
  become_user: "{{ service_user }}"
  systemd:
   name: "{{ service_systemd_name }}-container-pod-{{ service_user }}.service" 
   scope: user
   state: started

