---
# tasks file for service
- name: Prepare, build, install and enable {{ service_systemd_name }} service pod
  import_tasks: create_service.yaml
  when: service_state == "present"

- name: Disable and remove the {{ service_systemd_name }} services and user
  import_tasks: del_service.yaml
  when: service_state == "absent"

