- name: Ensure proxyd service for {{ service_systemd_name }} is stopped
  systemd:
    name: "{{ systemd_unit_name }}.service"
    state: stopped
    scope: system
- name: Ensure proxyd socket to {{ service_systemd_name }} is stopped
  systemd:
    name: "{{ systemd_unit_name }}.socket"
    state: stopped
    scope: system
- name: Ensure proxyd socket to {{ service_systemd_name }} is disabled at boot
  systemd:
    name: "{{ systemd_unit_name }}.socket"
    enabled: no
    daemon_reload: yes
    scope: system
- name: Del systemd stream socket(s) for proxyd for {{ service_systemd_name }}
  file:
    path: "{{ systemd_unit_file_basename }}.socket"
    state: absent
- name: Del systemd stream service(s) for proxyd for {{ service_systemd_name }}
  file:
    path: "{{ systemd_unit_file_basename }}.service"
    state: absent

