- name: Copy "{{ directory }}" on host
  become: true
  become_user: "{{ service_user }}"
  copy:
    src: "{{ servideo_config_dir }}{{service_systemd_name}}/{{ directory }}"
    dest: "{{ ansible_env.HOME }}/{{ directory }}"
    mode: "{{ mode }}"

- name: Set SElinux labels
  become: true
  become_user: root
  sefcontext:
    target: '{{ ansible_env.HOME }}/{{ directory }}(/.*)?'
    setype: {{ item }}
    state: present
  loop: "{{ selinux_labels }}"

- name: Apply new SELinux file context to filesystem
  command: restorecon -irv "{{ ansible_env.HOME }}/{{ directory }}"
  become: true
  become_user: root

