- name: Create "{{ directory }}" on host
  become: true
  become_user: "{{ service_user }}"
  file:
    path: "{{ service_homedir }}/{{ directory }}"
    mode: "{{ mode }}"
    state: directory

- name: Copy "{{ directory }}" on host
  become: true
  become_user: "{{ service_user }}"
  copy:
    src: "{{ servideo_config_dir }}{{service_systemd_name}}/{{ directory }}"
    dest: "{{ service_homedir }}/"
    mode: "{{ mode }}"

- name: Set SElinux labels
  become: true
  become_user: root
  sefcontext:
    target: '{{ service_homedir }}/{{ directory }}(/.*)?'
    setype: "{{ selinux_label }}"
    state: present
  loop: "{{ selinux_labels }}"
  loop_control:
    loop_var: selinux_label

- name: Apply new SELinux file context to filesystem
  command: restorecon -irv "{{ service_homedir }}/{{ directory }}"
  become: true
  become_user: root

