- name: Delete systemd {{ service_name }} service
  become: true
  become_user: "{{ service_user }}"
  vars:
    container_name: "{{ service_systemd_name }}"
    container_state: absent
  import_role:
    name: ikke_t.podman_container_systemd

